export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'

export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS';
export const SEARCH_LOCATION_FAIL = 'SEARCH_LOCATION_FAIL';

export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';